name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Setup Volta
        uses: volta-cli/action@v4

      - name: Install Dependencies
        run: |
          volta install
          pnpm install

      - name: Confirm Versions
        run: |
          volta --version
          node --version
          pnpm --version

      - name: Build
        run: pnpm run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: pnpm
